# Generated by Django 5.1.2 on 2024-11-10 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='volume',
            field=models.IntegerField(default=0),
        ),
    ]
