# Generated by Django 5.1.2 on 2024-11-10 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sv', '0002_price_volume'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ['-date']},
        ),
        migrations.RenameField(
            model_name='price',
            old_name='close_price',
            new_name='close',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='day',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='high_price',
            new_name='high',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='low_price',
            new_name='low',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='open_price',
            new_name='open',
        ),
        migrations.AlterUniqueTogether(
            name='price',
            unique_together={('stock', 'date')},
        ),
    ]
