# Generated by Django 5.1.1 on 2024-10-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sv', '0002_remove_price_time_remove_price_value_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='close_price',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='price',
            name='high_price',
        ),
        migrations.RemoveField(
            model_name='price',
            name='low_price',
        ),
        migrations.RemoveField(
            model_name='price',
            name='open_price',
        ),
        migrations.AddField(
            model_name='price',
            name='time',
            field=models.TimeField(default=0.0),
        ),
        migrations.AlterField(
            model_name='price',
            name='day',
            field=models.DateField(default=0.0),
        ),
    ]
