# Generated by Django 5.1.1 on 2024-10-09 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sv', '0003_rename_close_price_price_value_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='value',
            new_name='close_price',
        ),
        migrations.RemoveField(
            model_name='price',
            name='time',
        ),
        migrations.AddField(
            model_name='price',
            name='high_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='price',
            name='low_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='price',
            name='open_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='price',
            name='day',
            field=models.DateField(),
        ),
    ]
