# Generated by Django 5.1.1 on 2024-10-09 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sv', '0004_rename_value_price_close_price_remove_price_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ['-day']},
        ),
        migrations.AlterUniqueTogether(
            name='price',
            unique_together={('stock', 'day')},
        ),
    ]
