# Generated by Django 5.1.2 on 2024-11-10 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sv', '0004_alter_price_close_alter_price_high_alter_price_low_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='volume',
            field=models.BigIntegerField(default=0),
        ),
    ]
