# Generated by Django 5.1.2 on 2024-12-01 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sv', '0005_alter_price_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='neg',
            field=models.DecimalField(decimal_places=2, default=0.3, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='neu',
            field=models.DecimalField(decimal_places=2, default=0.333333, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='pos',
            field=models.DecimalField(decimal_places=2, default=0.333333, max_digits=10),
            preserve_default=False,
        ),
    ]
